SELECT 
DATA_CATCHCOMP_PWS_SPOTS.EVENT_ID,
DATA_CATCHCOMP_PWS_SPOTS.POT_ID,
Sum(DATA_CATCHCOMP_PWS_SPOTS.COUNT) AS SumOfCOUNT

FROM DATA_CATCHCOMP_PWS_SPOTS
WHERE (((DATA_CATCHCOMP_PWS_SPOTS.FK_SPECIES_CODE)="965"))
GROUP BY DATA_CATCHCOMP_PWS_SPOTS.EVENT_ID, DATA_CATCHCOMP_PWS_SPOTS.POT_ID
HAVING (((Sum(DATA_CATCHCOMP_PWS_SPOTS.COUNT))>0));
